name: Check for changes in gflanguages

on:
  push:
    paths:
      - '**.yml' 
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install GH CLI
      uses: dev-hanz-ops/install-gh-cli-action@v0.2.0
    - name: Run Script
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ..
        cp -r glyphsets glyphsets2
        cd glyphsets2
        pip install .
        pip install -U git+https://github.com/googlefonts/lang
        pip freeze
        cd ..
        diff -r glyphsets/data glyphsets2/data || gh issue create --title "Changes in lang data" --body "Changes in gflanguages lead to updated glyphset definitions" --label "gflanguages"