name: Check for changes in gflanguages

on:
  push:
    paths:
      - '**.yml' 
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Run Script
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ..
        cp -r glyphsets glyphsets2
        cd glyphsets2
        pip install .
        pip install -U git+https://github.com/yanone/lang
        pip freeze
        sh build.sh
        cd ..
        diff -r data/results ../glyphsets2/data/results || export DIFF=$(diff -r data/results ../glyphsets2/data/results); echo -e "Changes in gflanguages lead to the following glyphset definition changes:\n\n$DIFF" > BODY; cat BODY; export BODY=$(cat BODY); gh issue create --title "Changes in gflanguages data" --body "$BODY"
