name: Check for changes in gflanguages

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 23 * * 2'
  push:
    paths:
      - '**.yml'

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Check for changes in gflanguages
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ..
        cp -r glyphsets upstream
        cd upstream
        pip install .
        pip install -U git+https://github.com/googlefonts/lang
        pip freeze
        sh build.sh
        cd ..
        cd glyphsets
        export COMMAND='diff -r -x BODY -x .git -x _* -x build -x *.egg-info . ../upstream'
        eval $COMMAND || echo -e "Recent data changes in **gflanguages** lead to the following glyphset definition changes:\n\n" > BODY; echo -e '```diff' >> BODY; echo -e "`eval $COMMAND`" >> BODY; echo -e '```' >> BODY; cat BODY; gh issue create --title "Changes in gflanguages data" --body-file BODY --label "dependencies"
